name: Mac and Jacs
favicon: null
layout_spectrum: 0.9856631
typography_spectrum: 0.2419355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#45413F'
    - '#BBD85C'
    - '#6F6D6C'
    - '#D8D7D6'
  brandStrength: 1
  lightness: 0.811828
  saturation: 1
  rhythmicContrast: 0.7060932
purpose: []
