name: "Mac and Jac's"
favicon: null
layout_spectrum: 0.75144
typography_spectrum: 0.24579
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Mac & Jac's"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#45413F'
    - '#BBD85C'
    - '#6F6D6C'
    - '#D8D7D6'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
